### ISSUE TITLE
ImportError: No module named modules

### ISSUE THREAD

**Issue by Prestin32k** [abenassi/Google-Search-API#3]
Hi,

I tryed to install it mutiple times, manually, by pip nothing suits for me.
The following error is produced:

  File "C:\Python27\lib\site-packages\google\__init__.py", line 2, in <module>
    from modules import standard_search, shopping_search
ImportError: No module named modules

**Comment by abenassi** [comment]
Hi Prestin!

Sorry by the delay in answering, I didn't see the issue until now. Please try to do it again now (pip install Google-Search-API or manually), I fixed some mistakes in the setup.py file that I think were the problem, together with other things.

Please tell me if you could install it and use it! 
It would be good to know if you use the package, because I may clean up a bit, fix one or two things and finish to implement a few others... It's always more encouraging to do so when you hear from someone that actually wants to use it :-)
