### ISSUE TITLE
Filter by date

### ISSUE THREAD

**Issue by anath2** [abenassi/Google-Search-API#56]
Hi, is there a way to filter results by date in the search output?

**Comment by JuaniFilardo** [comment]
Hi, afaic there are not many google results that include the date of the page/article; could you send an example? As it's not so common, the date isn't included in the attributes of the GoogleResult object.
I guess you could add this attribute (as a datetime object, not the string) and then check if there's a date in the result, otherwise set it to None. Then filtering should be applied in your code.

PS: I just checked and when you manually search in Google you can go to Tools and change the parameter "Any time" to any of the other options (past year, past day, etc). I thought that was most likely to be set in the GET parameters, and so it is:

q=kurt+vonnegut&safe=off&client=psy-ab&hl=en-AR&source=lnt&**tbs=qdr:w**&sa=X&sqi=2&ved=0ahUKEwje5J_7lc7bAhWprVQKHblUDa8QpwUIIA&biw=959&bih=885

q=kurt+vonnegut&safe=off&client=psy-ab&hl=en-AR&source=lnt&**tbs=qdr:y**&sa=X&ved=0ahUKEwjRyc2cls7bAhWHn4MKHeWjBtIQpwUIHw&biw=959&bih=885

Pay attention to the bold part. The first one searches for results of the past week, while the second one searches the last year.
I'm pretty busy at the moment but if someone wants to, they can record every one of these options and then set a parameter in the code that passes the correct GET parameter in order to filter by date (users should also be able to select by which parameter they want to search, in the search() method). If I remember correctly, the feature of 'tuning' the URL belongs to utils.py.

**Comment by anath2** [comment]
I submitted a pull request for this :
https://github.com/BirdAPI/Google-Search-API/pull/2

**Comment by JuaniFilardo** [comment]
That's great. I quickly looked at your code and it seems alrigth, could you please also submit that pull request to this repo?
